### ISSUE TITLE
Personas for the bank app

### ISSUE THREAD

**Issue by iharsuvorau** [Sysmod-2021/bankappbackend#23]
- [x] Normal customer
- [x] Atypical customer
- [x] Bank administrator
- [x] Atypical bank administrator

**Comment by joannamjc** [comment]
![Linda Rand - Normal Customer](https://user-images.githubusercontent.com/93998511/142768557-07743b9f-fca3-4ab6-9f52-c0ae98ebeb40.png)

**Comment by joannamjc** [comment]
![Markus Kull - Normal Admin](https://user-images.githubusercontent.com/93998511/142768859-602be804-50d0-45fb-bb20-e3d9a9c93226.png)

**Comment by joannamjc** [comment]
![Markus Kull - Normal Admin](https://user-images.githubusercontent.com/93998511/142769260-09081a4d-faf8-47de-a9f8-1713d0a085d3.png)

**Comment by joannamjc** [comment]
First two personas are normal customer and normal bank administrator, respectively. Atypical personas will be posted below.

**Comment by joannamjc** [comment]
![Toomas Sepp - Atypical Customer](https://user-images.githubusercontent.com/93998511/142770811-a9b9216d-7b01-4d98-b9d7-220ea14666d5.png)

**Comment by joannamjc** [comment]
![Jaanika Kangur - Atypical Admin](https://user-images.githubusercontent.com/93998511/142771536-bf130b6a-332f-4b40-b51e-5675c2401a9b.png)

**Comment by iharsuvorau** [comment]
@joannamjc great, thank you

**Comment by joannamjc** [comment]
There are two target user groups for Open Demo Bank App, a bank employee, who concurrently serves as the account administrator, and the bank customer. Personas were created with these users in mind and how the application will help them in their day-to-day activities.

A typical bank employee will be using the system to carry out their daily responsibilities in the bank. What makes them typical is that they are full-time employees of the bank, which is an institution generally known for putting up high security measures in their systems. So these typical bank employees are allowed to carry out processes in the system based on the access level they are assigned.

A typical customer will most likely be using the system as a mobile application. These customers will have made the application a part of their lifestyle because they are those who regularly transfer money to other people, may it be their families, friends, colleagues, and others. As such, the product must be rewarding for them to use.

An atypical employee was also considered in designing the application. This kind is a part-time employee of the bank, who is hired only during peak seasons. This means that access level and security may be different or limited for this user. They also may or may not be able to use all functionalities of the system or they may use the system in a device different from the usual desktop a full-time employee uses.

The atypical customer that was considered in designing the application is someone who might use the system sparingly. This can be someone who does not really need to use the app that much and will only benefit from it from time to time. While these customers might be atypical, their needs were also considered. In this case, someone of poor hearing and eyesight needs to have accessibility options in the application.

@iharsuvorau
