### ISSUE TITLE
Use case diagrams

### ISSUE THREAD

**Issue by iharsuvorau** [Sysmod-2021/bankappbackend#25]
We need use case diagrams based on user stories from https://github.com/Sysmod-2021/bankappbackend/issues/24#issuecomment-970852232

**Comment by joannamjc** [comment]
Use Case Diagram for FR #1, FR #7
![(1) Admin - Account Creation](https://user-images.githubusercontent.com/93998511/144146491-3f72d5bb-365f-4d8c-8971-b1070529891d.png)

Use Case Diagram for FR #7, FR #8, FR #12
![(2) Customer - Account Overview](https://user-images.githubusercontent.com/93998511/144146514-d0b83b0a-d47b-484a-8a6e-33511a9fd474.png)

Use Case Diagram for FR #7, FR #9, FR #10
![(3) Customer - Transaction Overview](https://user-images.githubusercontent.com/93998511/144146563-e61e0c6c-d06e-43ca-b61a-41d43cfe5d3b.png)

**Comment by joannamjc** [comment]
Use Case Diagram for FR#2
![(4) Admin - Transaction Creation](https://user-images.githubusercontent.com/93998511/144148171-e1024049-4011-40bf-9e30-f41a8f2db1a2.png)

Use Case Diagram for FR#4
![(5) Admin - Seed Transaction Creation](https://user-images.githubusercontent.com/93998511/144148198-b76d9ea9-3840-4be1-bb65-973ba625a872.png)

**Comment by joannamjc** [comment]
Use Case Diagram for FR#3
![(7) Admin - Transaction Processing](https://user-images.githubusercontent.com/93998511/144150170-0067f1f5-4d3e-4b64-ba73-f601cea27721.png)

Use Case Diagram for FR#11
![(6) Admin - Account Modification](https://user-images.githubusercontent.com/93998511/144150219-64789aa7-940c-484c-a6b5-9e70ce9ec372.png)

**Comment by joannamjc** [comment]
Use Case Diagram for FR#5, FR#100
![(8) Customer - Transaction Execution](https://user-images.githubusercontent.com/93998511/144150973-fa9c5d15-c054-41f1-b909-a755d5167639.png)

**Comment by joannamjc** [comment]
The Open Demo Bank App provides a simple feature to be able to transfer money between customers of a bank or from a non-customer through the bank's mediation. This addresses the problem of finding simple, openly available banking solution for funding pitches and presentations for several start-ups. As required, with this application, two user groups, the Administrator and the Customer, will be able to:

**Admin**
- Create account
- Create transaction
- Modify transaction
- Make seed transaction
- Transfer money

**Customer**
- Transfer money

Functionalities were grouped according to their scopes and use cases were designed according to those groupings.

Use Case Diagram for FR#1, FR#7 - **Account Creation and Access**
Use Case Diagram for FR#7, FR#8, FR#12 - **Account Information**
Use Case Diagram for FR#7, FR#9, FR#10 - **Transaction Information**
Use Case Diagram for FR#2 - **Transaction Creation**
Use Case Diagram for FR#4 - **Seed Transaction Creation**
Use Case Diagram for FR#3 - **Transaction Processing**
Use Case Diagram for FR#11 - **Account Modification**
Use Case Diagram for FR#5, FR#100 - **Peer-To-Peer Transaction**

@iharsuvorau 
_FYI: We do not have anything labelled FR#6 in the Product Spec doc, that's why this list might seem that it's missing._
